### ISSUE TITLE
Source code for Moon2 does not match Moon2 binaries

### ISSUE THREAD

**Issue by MattF42** [avgttt/PePe-core#12]
Building from source results in PEPEPOWd with a version of  v1.2.3.1-g 
Can you please update the available source code tarball/zip.

Thanks

**Comment by avgttt** [comment]
![image](https://github.com/avgttt/PePe-core/assets/117731256/e083614e-c874-4d1e-90d5-227418d01309)

**Comment by MattF42** [comment]
I checked out the master branch and it builds (after tweaking to make it build on Ubuntu 22.04) and runs with the correct version. Thanks. It's just the source.tar.gz and source.zip in the releases which is wrong.  Thanks
