### ISSUE TITLE
Sync and Connection Problem

### ISSUE THREAD

**Issue by esenocak** [avgttt/PePe-core#3]
There are still problems in v0.3 about the connectivity in windows environment. Connection to the peers drops quickly and sync take too long.

**Comment by Pavluha161** [comment]
Для ускорения синхронизации кошелька QT:
Можно прописать сразу после первого запуска кошеля. Идём вверху в инструменты - консоль отладки и там отправляем команду (я отправлял по одной):
addnode "81.91.189.54:8900" "add"
addnode "8.217.38.226" "add"
addnode "8.217.90.111" "add"
addnode "136.35.64.48:8833" "add"
addnode "8.218.61.142:8833" "add"
addnode "185.119.58.221:8833" "add"
